name: Flask App Test

on:
    pull_request:
        branches:
            -main
jobs:
    test:
        runs-on: ubuntu-latest
        defaults: 
            run:
                working-directory: ./app/

        strategy:
            matrix:
                ptyhon-version: [3.8]

        env:
            MODE: "dev"
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions-setup-python@v4
              with: 
                  python-version: ${{ matrix.ptyhon-version}}
                
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ../requirement.txt
            - name: Test App Code
              run: python ./main_test.py
